parameters:
  app:
    name: Application name
    base_url: http://localhost/
  date:
    timezone: Europe/Paris
  locale: eng # Windows style ('en_US' otherwise)
  localisation:
    latitude: 45.0
    longitude: 5.0
  database:
    host: 192.168.1.2
    port: 3306
    user: root
    password: password
  weather_providers:
    openweathermap:
      api_key: PUT_YOUR_API_KEY
    weatherunderground:
      api_key: PUT_YOUR_API_KEY
  music_providers:
    deezer:
      app_id: PUT_YOUR_APP_ID
      secret_key: PUT_YOUR_APP_SECRET
  calendar_providers:
      google:
        primary_id: PUT_YOUR_GMAIL_EMAIL_ADDRESS
        other_ids: []
  transport_providers:
      metromobilite:
        favorites:
          stops:
            STOP_ID_1:
              rank: 1
              routes: [ROUTE_ID_1]
            STOP_ID_2:
              rank: 2
              routes: [ROUTE_ID_1]
            STOP_ID_3:
              rank: 3
              routes: [ROUTE_ID_2]